console.log(window.location.href);
let currentURL=window.location.href;
let baseURL=currentURL.substr(0,currentURL.length-12);
console.log(baseURL);

const dashboardLink=document.querySelector("#dashboard");
const claimActivityLink=document.querySelector("#claim-activity");
const customerAttentionLink=document.querySelector("#customer-attention");
const agentAttentionLink=document.querySelector("#agent-attention");
const completedRecentlyLink=document.querySelector("#completed-recently");
const recentDecisionsLink=document.querySelector("#recent-decisions");
const appellateActivityLink=document.querySelector("#appellate-activity");
const workInProgressLink=document.querySelector("#work-in-progress");
const recentDecisionsAALink=document.querySelector("#recent-decisions-aa");
const recentHearingsLink=document.querySelector("#recent-hearings");
const reportsLink=document.querySelector("#reports");
const activityLink=document.querySelector("#activity");
const trendLink=document.querySelector("#trend");
const chargeLink=document.querySelector("#charge");
const proactiveUploadLink=document.querySelector("#proactive-uploads");
const taxDocumentsLink=document.querySelector("#tax-documents");
const messageUiTeamLink=document.querySelector("#message-ui-team");
const userManagementLink=document.querySelector("#user-management");
